// blog.js
const posts = {
  post1: {
    id: 1,
    title: "French Open 2024",
    synopsis:
      "A proper French Open, with Alcaraz and Swiatek declaring themselves tennis royalty.",
    author: "Robert Hooker",
    date: "July 7, 2024",
    image: "carlos.jpg",
    content: `
            <p>As we look onto Wimbledon I want to get my thoughts down on Roland Garros this year. Premium sport, bizarre interactions, beautiful aesthetics, and historic victories were all had in Paris over these two weeks, and the tournament delivered as tennis slams so often do. With that I want to highlight some moments and hand out superlatives for what makes this tournament my favorite.</p>
	          <p>Best Vibe: Tomas Machac</p> 
            <p>With his short shorts and the movement of a natural born clay player, Machac was a joy to watch during the first week of this tournament, although eventually falling to Daniil Medvedev 7,6,1,&6. During that match however, Tomas played a point where he was forced to switch to his left hand twice, with the second being a winner up the line! At this point in his career Machac is pretty raw, but he has all the shots and is electric to watch. Unfortunately as we depart from the clay his chances of making a run at a major are much lower, but I will still be tuning in for his matches after seeing him flash at Roland Garros. Tremendous Vibe.</p> 
	          <p>Most Intrigue: Naomi Osaka</p>
            <p>This tournament felt like the re-coming out party for Osaka, which is odd considering she lost in R2. Not having won a grand slam since the Aus Open in 2021, everyone in the tennis world has been hopefully awaiting her return to glory. In between, Osaka has been a strong social justice advocate, questioned her place in the world, and recently had a child. To be at her level of fame at such a young age, it seems inevitable that the pressure of the media and expectations would cause some internal conflict, and you have to feel for athletes in such a position. BUT, now that she seems to have a new appreciation for tennis, the game has delivered, and her matches are back to being appointment viewing. Losing in the second round 7,1,&7 to Iga Świątek in an absolute hitting exhibition, she proved to be the only player who could come close to Iga’s level. So, even though it was a second round exit, if Osaka can maintain this level and improve her seeding, she will be a legitimate threat this fall on the hard courts of the U.S. Open.</p> 
	          <p>Best Player: Iga Świątek</p> 
            <p>The queen of clay. Once Iga moved past Osaka she was untested by her opponents. Now the winner of 4 of the last 5 French Opens, her level here almost made the women’s side of the tournament boring, if it weren’t for the history she was writing. Obviously it has been seen before that a player takes such a liking to the clay that it seems there will be no other champions for the foreseeable future, namely Rafael Nadal. These comparisons are only natural, and it doesn’t seem to phase Iga with her mindset, which is very humble and she seems to take tennis one point at a time. Projecting out however, she is only 23 and has 4 French Open titles, so I’m ready to give her 10.</p>  
	          <p>Best Guy: Casper Ruud</p> 
            <p>Nobody dislikes Casper Ruud, how dare you dislike Casper Ruud. He made another run at the French to year, making it to the semi-finals and where he would lose to Zverev. It should be on the record that Ruud was battling a stomach bug, which would later be found out to be a parasite!!! Anyhow, I don’t think there was anyone in Paris who wanted to see Zverev beat Ruud, so this was a tough one to swallow. Also tough was that Djokovic was not able to play in their quarterfinal, which would have been an amazing battle on the clay of Philippe Chatrier. I wish I walked around with the grace and class that Casper does, he’s just a great guy. I’ll add that it's a shame we are into the grass season, which he is ‘allergic to’, but I have strong hopes for him in Brooklyn this year.</p> 
	          <p>Most Significant: Carlitos Alcaraz</p>
            <p>The results speak for themselves for Carlos at Roland Garros 2024. He beats Sinner and Zverev in back-to-back five set matches to become the youngest man to win slams on all three surfaces. In doing so he also improved his five set record to 11-1(?), which, I mean, what the hell is that? I feel like it gets lost in his exuberant, considerate attitude, but this record shows that he has a killer mentality when it comes to grand slam tennis, and I believe is the reason he will win double digit slams. With Djokovic withdrawing from this tournament, it really feels like we are moving into the next generation of tennis greats here, and there is no more exciting player to be at the helm of it than Spain’s golden boy. I hope that we get to see a final changing of the guard between Alcaraz and Djokovic, considering the other worldly matches they played last season at Wimbledon and The Western & Southern, I feel like Nole deserves another shot at him in a major.</p>   
            <p>Cigarettes & Small Coffees, I love the French: Moutet vs Sinner</p>
            <p>This match was the French’s last hope at having a countrymen win this season, and they were out in full force. This match was played until around 3 am, and the whole vibe seemed to embody what I love about this tournament. The aesthetic of the clay was, as always, incredible, and the French crowd had all the chants going, as well as the drums thundering down from the rafters (so sweet). Although there was no chance Moutet was ever going to beat the No. 1 to be, he was the perfect player for this match. He was junk balling all over the place, yelling at the umpire, and complaining to his coaches box. There are no people who have mastered the look of disgust more than the French, and I find it truly aspirational.</p>

        `,
  },
  post2: {
    id: 2,
    title: "On the Financialization of Housing",
    synopsis:
      "Juggling the economy, equality, and new grads paying $2k a month in NYC",
    author: "Robert Hooker",
    date: "July 24, 2024",
    image: "nyc.jpg",
    content: `
            <p>This essay was spurred by the <a href="https://www.ohchr.org/en/statements/2017/03/statement-special-rapporteur-right-adequate-housing-leilani-farha-during?LangID=E&NewsID=21264" target="_blank">‘Statement by the Special Rapporteur on the right to adequate housing, Leilani Farha, during the Interactive Dialogue at the Human Rights Council’</a> in March 2017.</p>

            <p>In her statement, Farha advocates for the definancialization of housing and insists on the necessity for governments to consider housing a human right. She explains how financial corporations are buying up residential real estate and pricing less wealthy individuals out of their communities. This brings rise to her argument that States need to regulate financial intermediaries such that they align with ‘The New Urban Agenda’. I see that by implementing moderate reforms and regulations, we can protect vulnerable populations and promote social equity without stifling the economic benefits that investment in the housing market can bring.</p>

            <p class=p-header>The Human Right to Housing</p>
            <p>The human right to housing and equitable access to it are fundamental, as in today's world, lacking a decent living space significantly hinders an individual's ability to achieve prosperity and contribute to society. With that, the absence of it has a negative effect on society as a whole, especially in the case of children, where great potential goes unrealized due to the immediate obstacle of surviving in harsh living conditions. So, regulators and institutions alike should adopt the theory of longtermism applied to housing, in doing so promoting posterity. Such strategies in housing can reduce future public expenditures on healthcare, social services, and crime prevention while fostering a more stable and productive workforce.</p>

            <p>Investment in affordable housing not only meets a basic human need but also stimulates economic growth. It generates jobs in construction, real estate, and related sectors, boosting local economies. Additionally, increased housing affordability allows households to spend more on other goods and services, further stimulating economic activity​ (<a href="https://www.habitat.org/" target="_blank">Habitat for Humanity</a>)​. This outcome is not hindered by the financialization of housing; rather, it is supported by it when managed correctly. Effective financialization involves ensuring that investments in the housing market prioritize the development of affordable units and community benefits, thus aligning financial incentives with social objectives.</p>

            <p class=p-header>The Benefits and Risks of Financialization</p>
            <p>While Farha denounces housing as a commodity, it tends to have underlying benefits including capital investment and economic growth, increased housing supply, and a robust economic multiplier effect. The prospect of return on real estate investment brings capital into the housing market, whether it be from individuals, private equity, REITs, or institutional investors. This money can be used to fund housing projects which bolster communities and promote further economic growth. This can result in a feedback loop in which children raised in prosperous areas have full access to education, and can then contribute to the already thriving community.</p>

            <p>To this point, the additional investment can increase the supply of housing. This works hand in hand with housing as a human right, as with homelessness and eviction there is a demand for housing. This, of course, is contingent upon the housing being affordable, which seems to be the current point of inflection in this discussion. This construction of the new housing supply should also theoretically breed innovation, and potentially cut costs of building homes. These lower costs should reflect lower prices in a free market, however, this reflection does not tend to be the case in reality, as seen in the 2007 housing bubble.</p>

            <p>As Farha notes, global real estate is the largest asset class, intertwining housing with various other economic sectors. Consequently, each dollar invested in the housing market generates additional dollars in related industries, such as construction, real estate services, and retail. This economic multiplier effect can help sustain high levels of economic growth and promote broader societal prosperity.</p>

            <p class=p-header>Current Challenges</p>
            <p>It seems in our current state, the financialization of housing is not working for the causes outlined above, rather the <a href="https://fred.stlouisfed.org/series/CSUSHPINSA" target="_blank">home price index</a> continues to rise, pricing lower-income individuals out of their communities. Unfortunately, this gentrification is in large part due to the speculation on housing as an investment vehicle, which has continuously shown attractive returns to investors. This can be seen in cities such as New York or London, where housing prices are generally agreed upon to be insane compared to the income level.</p>

            <p>This situation poses a significant risk not only to individual housing consumers but also to the macroeconomy. A speculative bubble occurs when the price of an asset rises rapidly and unsustainably, often fueled by market hype rather than fundamental economic value. The collapse of such a bubble can trigger widespread economic downturns, as witnessed during the 2008 financial crisis. The question arises: are financial institutions, like BlackRock, which are heavily investing in housing, contributing to the formation of a bubble? If so, has the Dodd-Frank Act, which was designed to increase financial regulation and prevent another crisis, failed in its mission, or will it help mitigate a potential downturn?</p>

            <p>Regardless of whether a bubble is forming, the current trajectory of housing prices poses a severe challenge for lower-income families. These families are increasingly being priced out of their communities and forced into neglected neighborhoods with fewer resources and opportunities. This displacement not only disrupts their lives but also exacerbates social inequalities and tensions, as marginalized populations are concentrated in under-resourced areas.</p>

            <p class=p-header>A Proposed Balanced Approach</p>
            <p>Finally, I believe there exists an approach to the housing situation which can result in housing for all without completely definancializing the system or hurting the macroeconomy. This involves regulating financial housing markets accordingly, incentivizing investment in affordable housing, and protecting vulnerable groups.</p>

            <ul>
                <li><strong>Regulation:</strong> Impose further taxes on speculative real estate investment, thus defending against price bubbles.</li>
                <li><strong>Promote Investing:</strong> Grant breaks from such taxes when investors allocate a certain amount of new capital towards new affordable housing developments. Governments should collaborate and contribute to funding the private sector in building affordable housing.</li>
                <li><strong>Protection:</strong> Provide state-supported legal aid for tenants facing evictions and disputes. Offer state-provided housing alternatives (shelters, subsidies) for evicted and homeless individuals. Ensure that a portion of gains from housing investments is reinvested into the community.</li>
            </ul>

            <p class=p-header>Conclusion</p>
            <p>In conclusion, the financialization of housing presents both challenges and opportunities. While Farha argues for the definancialization of housing to protect human rights, I feel that with appropriate regulation, financial markets can play a crucial role in addressing housing needs. Financialization, when managed correctly, can bring significant capital into the housing market, stimulate economic growth, and increase housing supply. However, it is essential to implement safeguards against speculative bubbles, promote investments in affordable housing, and protect vulnerable populations from displacement. By adopting a balanced approach that includes stringent regulations, incentives for inclusive investment, and robust protections for low-income families, we can harness the benefits of financialization while ensuring that housing remains accessible and equitable for all. This strategy will not only uphold housing as a fundamental human right but also contribute to sustainable economic and social development.</p>

        `,
  },
  post3: {
    id: 3,
    title: "Chicago Architecture Tour",
    synopsis:
      "On a recent visit to chicago I got the chance to walk around town a bit and admire the architecture. ",
    author: "Robert Hooker",
    date: "July 31, 2024",
    image: "river.jpg",
    content: `
    <p>As charming as European cities are, there is something I’m drawn to with the grand, industrious cities of America. Chicago's downtown, in particular, seems to exude a sense of importance. It's easy to imagine that significant work is being done in these buildings, which is inspiring to me. In my opinion, the city has done a really nice job juxtaposing their historic structures with the more contemporary, such that most of the buildings don’t feel out of place. With that, I’d like to highlight some of my favorites which I think are examples of exemplary cityscape architecture.</p>
    
    <h2>111 South Wacker Drive</h2>
    <img src="assets/111.jpg" alt="111 South Wacker Drive" class="blog-image">
    <p>As far as modern high-rise office buildings go, I think this one does a nice job of not being over the top, while maintaining a sense of personality. Completed in 2005, the building has done well to be timeless, in the sense that it does not seem caught in the middle ground of historic and modern, where some skyscrapers find themselves. What I appreciated most about this building was the open base that you see in the image. This is not the first of its kind, but I think this type of design should be applauded as it makes a noticeable difference in the building's footprint, and makes walking around the building much more enjoyable. Finally, I love the way the architect uses the reflective glass, yet still puts some character into the structure via the vertical louvers and extrusions.</p>

    <h2>Chicago Board of Trade</h2>
    <img src="assets/cbot.jpg" alt="Chicago Board of Trade" class="blog-image">
    <p>The CBOT building, now where CME is located, is one of the historical buildings in Chicago that I feel remind you that you’re in an important center of the country’s development. I think I mostly feel this way because to build such an imposing, yet elegant structure in 1930, your city must’ve been an epicenter for commerce. On this, the way the Wintrust and Federal Reserve Bank buildings frame it from this view, they almost act as sister buildings in this really nice, timeless financial district. And of course, who doesn’t love a grand clock on a building.</p>

    <h2>Art Institute of Chicago</h2>
    <img src="assets/aic.jpg" alt="Art Institute of Chicago" class="blog-image">
    <p>Of course, being an art institute, you’d expect an aesthetically pleasing structure, but this truly stands out in the center of downtown Chicago. I find the ancient Greek and Roman architectural style of this building very fitting for its location. It emanates art and culture, standing out amidst the surrounding hustle and bustle of business. The lions are also sweet.</p>

    <h2>875 North Michigan Avenue (John Hancock Center)</h2>
    <img src="assets/875.jpg" alt="John Hancock Center" class="blog-image">
    <p>Finished in 1969, the JHC had to be a modern marvel at the time. It's the fifth tallest building in the city, yet I find it belongs in the same category as the Willis Tower, especially evident when driving into the city. The JHC also reminds me of the Transamerica Pyramid in San Francisco, but the deep black color has almost given it a contemporary look. I think the real appeal here is how it frames itself with Lake Michigan, as seen in the picture above.</p>

    <h2>435 North Michigan Avenue - Tribune Tower</h2>
    <img src="assets/tribune.jpg" alt="Tribune Tower" class="blog-image">
    <p>Maybe saving the best for last here, the detail of the Tribune Tower’s gothic design really stands out amongst American buildings. The base and top of the building really remind me of an old Spanish Catholic church, but there happens to be (now) 36 floors of luxury residences in between. I honestly can’t imagine there is a more classy building to call home in the city.</p>
    <p>There are a lot of other great buildings, but I found these five to best represent the character of Chicago in 2024, and they all have great design features. Thanks for reading!</p>
        `,
  },
  post4: {
    id: 4,
    title: "A People's History of the United States: Chapter Notes",
    synopsis:
      "Howard Zinn had a polarizing stance on U.S. History, these notes are to help me understand his writing and outlook. A fascinating endeavor thus far.",
    author: "Robert Hooker",
    date: "Updated July 22, 2024",
    image: "bostonmass.jpg",
    content: `
            <p class=p-header>Chapter 1: Columbus the Indians and Human Progress</p>
            <p>In this first chapter Zinn establishes / points out his gripe that history is too often told by “governments, conquerors, diplomats, [and] leaders” This ultimately begs the question in this first chapter of whether the demolition of hundreds of thousands (millions?) of Native American people could be chalked up as a discerning but necessary course of action in the interest of progressing humanity? Considering Powhatan’s plea to John Smith (in short): “Why will you take by force what you may have quietly by love?” Does it make sense to glaze over the prospect of indigenous people because they were a few hundred years less technologically advanced (in warfare) than the whites who landed upon their shores. Indicators other than their lack of gunpowder point to them being a more advanced society, i.e the likes of their community supports, lack of class system, connection to nature and fellow human, and democratic governance with women in prominent roles. To think that these values (best summarized by Powhatan’s plea) could have been extrapolated onto the current growth of western civilization, makes it hard to believe that we would not be better off. An interesting argument is that the competitive early stage capitalist society is the reason that the whites were more advanced in warfare, and would inherently prevail in any iteration of the meetings between whites and indians. Anyhow, it is important to be critical when someone tries to use the progression of humanity as an excuse for atrocities and genocide in the worst case, as it is still genocide, and the victors will always preach that this outcome (them winning) was ideal and progression towards human prosperity.</p>
            <p>**Also in this chapter Spanish conquistadors pillage and destroy both the Aztecs (Cortes) and the Incas (Pizarro) in similar manner to Columbus and the English settlers of VA/MA. The fascinating part about the Aztec and Incas was the lack of global information at the time was so great, that when these conquistadors showed up on horseback on their beaches, they were believed to be divine. This made the jobs of Cortes and Pizzarro much simpler, which was of course to smash the entire civilization (both are now lost) and take all their gold!</p>
            <p class=p-header>Chapter 2: Drawing the Color Line</p>
            <p>This chapter details how slavery came to be in America and the dynamics that lead to 300+ years of racism. The question Zinn gets at is whether this racial divide is always and forever, or if it was manufactured. The first African slaves were in small numbers in Lisbon, but quickly became the norm. In the colonies' case, they were the best candidate as the whites would never be able to control the Native Americans as they had far too much knowledge of the land and know-how. Taking Africans and placing them in the New World, however, left them almost hopeless, especially considering the horrendous voyage forced upon them to get there in the first place. Even still the masters had to instill hatred and manufacture fear in the slaves to prevent revolt, these methods are well documented, both physically and mentally. Even still the slaves revolted and fled in instances, more so in the first generation, but slaves born slaves were more grained into the system. With slave numbers increasing rapidly, masters became more fearful of these revolts. Out of this, they decided to give more rights and prosperity to the poor whites and white indentured servants, as to separate them from the possibility of assisting in/procuring a revolt akin to Bacon’s rebellion, only on a larger scale. The massive profit incentive of owning a plantation (and other slave employs) was enough for the upper class to create policies dividing the lower class whites (who were also being thrown small incentives) and slaves, so as to avoid revolt and keep their cash rolling in. In this however, they introduced racism which would evolve and reverberate throughout the following centuries of their yet to be formed countries’ history.</p>
            <p class=p-header>Chapter 3: Persons of Mean and Vile Condition</p>
            <p>These people of ‘mean and vile condition’ being the lower class of the early colonies, whose population grew and were ever looked over. People continued to come across to the New World for various reasons, and as the new cities (Boston, New York, Philadelphia, Charleston) became more populated, this class of utterly poor individuals accumulated. At the same time, throughout the 18th century the wealth started to accumulate more and more towards the top of the population, where in 1770 1 percent of property owners in Boston owned 44% of the wealth. Also put in place were policies favoring the upper upper class, as they were the ones making the policies. Most of these centered around land rights where all the land was distributed to an absurdly small number of proprietors. These proprietors could then ‘sell’ the land for pennies on the dollar to people of whom it was in their best interest to keep happy for future business (this is the most American bourgeoisie shit of all time). With this however, you might expect revolts from the populus, and during these ~150 years of the colonies figuring it out, there were a ton of revolts. Strikes were also common, although that looked more like just not showing up for work. Government officials and people of power were killed, merchants and masters as well, and the unrest ultimately struck the high society with the same fear that slave masters had. Considering this they need to get more people on their side, and through social manipulation and granting incentives for the ‘common man’ (whatever that is in this era (or any)), they created the middle class!! This middle class would be loyal to the elites as they were taken care of, and eventually “through language of liberty and equality” they would start a revolt of their own against the motherland: England. It seems king george VIII could have learned from the slave masters in their cautions against revolt, but also it seems no one can oppress forever.</p>
            <p>**Chapters 2 & 3: The 17th and 18th century upper class manufacture both racism and the middle class / American class system?</p>
            <p class=p-header>Chapter 4: Tyranny is Tyranny</p>
            <p>This chapter details the events and public sentiment leading up to the American Revolution. Themes of hypocrisy, social manipulation, and classism are all behind the revolution, and the motives echoed by the upper class. It has been almost famously recognized how hypocritical the ‘unalienable rights’ of Life, Liberty, and The Pursuit of Happiness were at the time. Although equality is hard to define and still a concept we as a society grapple with, these rights were truly reserved for white males, and an obviously astray from equality. Zinn notes that the point of studying this history is not to condemn the founding fathers, but rather to better understand how they got to the declaration, its motives, and how we can learn from it. In this case the middle and lower-middle classes were mobilized through language of liberty and equality. The upper class used such languages in speeches and pamphlets, pinning the people against the current ruler, England, and painting a facade that they (the upper class) were also the common man, being exploited by George VIII and parliament. The irony here both that in their new society liberty and equality would only exist for the white men, which contradicts itself, and that the populus will still be subject to the command and control of the upper class. This is recognized immediately by those with a keen eye for bullshit at the beginning of the revolution. When the Boston Committee of Correspondence organized the draft for the revolution, the rich were able to pay their way out of it, and the chants were heard: “Tyranny is Tyranny let it come from whom it may”.</p>
            <p>**Thomas Jefferson had authored an entry for the Declaration that in summary denounced the slave trade, and put it at fault of the king. This was removed because members of the continental congress wanted to keep their slaves. It is also a puzzling paragraph considering Jefferson himself owned hundreds of slaves and famously had multiple children with them.</p>
            <p class=p-header>Chapter 5: A Kind of Revolution</p>
            <p>This chapter speaks of the revolution against England, of course not going into detail about the battles, but more understanding motives and techniques used to mobilize colonists into revolution. It was clear that there was a large portion of people living in the colonies who were not thrilled about the idea of a revolution. These groups are mainly the loyalists, slaves, indians, and poor whites. With this knowledge the aristocracy had to find a group that they could mobilize into soldiers to fight their war. Originally this meant people of “full citizenship”, i.e. middle class white citizens, but quickly the revolutionary army became desperate, and began recruiting lower class whites, offering an opportunity to perhaps rise in rank and acquire some money. This however would not be the case for the lower class, as they would generally be drafted into lower ranks, not making enough money to combat inflation, and serving through many battles. On the contrary upper-middle class soldiers were drafted into higher ranks, where they could earn 10x+ what the lowers were, and exit early with profit and health. This dynamic would increase the gap between upper and lower class over the course of the war, and it can be argued that this was one of the main motives of the war. Eventually these lower classes would be impressed into the war by the aristocracy, which garnered comparisons to the British rule, people noting that this behavior will only lead to distaste for the government and eventually bloodshed.</p>
            <p>This foreshadowing ended up being correct. During the war these lower class people, along with their low pay, were given small amounts of land to farm and live off of as compensation for their enlistment. The land given to them however, came with debt owed to the new ruling class of America, so these freeholders found themselves in much of the same situation as before the revolution, only now paying off debt to a bank rather than a landlord.</p>
            <p>For native americans the revolution simply meant that they were all alone with the Americans now. The British, who sometimes brokered fair deals with them, were gone, along with their former allies the French. Thus began the pushing out and extortion of the natives, as Americans would slowly but surely seize their land and kill at the sign of resistance. Any chief of tribe who has dealt with Americans by this point is well aware that the word or contract of them has no meaning, and when their situation requires it, they will come for this land to. With this notion, more interactions led to war, only it wasn’t the elites who wanted the land fighting, it was the poor frontiersman who had been pushed out of the east by those elites.</p>
            <p>For blacks, the revolution somewhat marked the beginning of their own. In the sense that free blacks started to make demands of the upper class that had controlled them for ~300 years. Citing the fact that they were being taxed without representation, the exact thing that they had just fought for in the Revolution. Benjamin Banneker, a black man, asked Thomas Jefferson ‘to wean yourselves from those narrow prejudices which you have imbibed.’ Explaining to Jefferson that they are one in the same.</p>
            <p>So what was the revolution actually for then? It seems that it was an effort of the colonial aristocracy to seize the controlling and wealthy position from the British elites/landlords. There was an immense amount of wealth and land to be had if they could get rid of the British and control the colonies as one nation. In the Federalist’s papers by James Madison, Alexander Hamilton, and John Jay, the sentiment and motive of separating the rich and poor, and the power to control the masses can be observed. Madison speaks of having a republic that rules over all 13 states, such that it makes it hard for uprisings to spread across state lines. This is concerning, as if there was a sentiment that would spread across the population, one would think it should be able to, such that it can be addressed and acted upon. This suppression of public opinion is also seen in FP #63, where they argue for the senate as “sometimes a necessary defense to the people against their own temporary errors and delusions.”.</p>
            <p>With that it is seen that the constitution was in large part incentivized by the aristocracy’s goal of taking and maintaining power and wealth. In doing so they would also need to grant certain citizens some amount of rights/liberties in order to have enough support from the population, so they could maintain control. This middle class group of small landowners and laborers who were slightly better off than the average worker of this time period acted as a buffer between the elites and the mass of people suffering (slaves, white servants, indians).</p>
            <p>In short the upper class at the time of the revolution believed they were better off making the decisions for the country, and took deliberate steps to ensure their power and wealth over a large lower class who “are turbulent and changing; they seldom judge or determine right” (Hamilton). These steps included the similar oppression as pre revolution: not paying soldiers, charging them for land ‘given’ to them and ensuring that only the wealthy could take part in politics. These steps caused rebellion, such as Shays, and many court hearings on debt charges were adjourned, however eventually the government sorted these out and their power became immense.</p>
            <p class=p-header>Chapter 6: The Intimately Oppressed</p>
            <p>Through the first five chapters of the book, Zinn hardly mentions women. I believe this is a deliberate attempt to help the reader realize how overlooked they were in colonial and early American society. Here however, he gets into the unique and extreme level of oppression these women faced. I think an important note in their specific oppression is that this treatment of women was not universal, as pointed out earlier, native american women were involved in politics, war, and adopted the man into their house, rather than vice versa.</p>
            <p>One of the factors which made this oppression unique was the isolation which women were forced into. Practically slaves to the home and their children, women never had the opportunity to socialize with each other, furthermore they couldn’t gather to get any sort of revolution under way. It was only during and after the revolution, when the production level required women to maintain itself, that women would join together and eventually start to protest the conditions they were forced into.</p>
            <p>What they were protesting was the system in which they were brought up, or brought into. For early colonists women, they were literally sold into a marriage in the new world, shipped across the Atlantic, and forced to work, treat, and please their husband. As the colonies became more established, the education of women was as well. This was not any sort of formal education as we know it, but rather ingrained in young women what they were to become. Through methods including religion, force, and psychological manipulation, colonial women were taught that they were to be obedient, loving, loyal, and above all serve their husband and family.</p>
            <p>Once they began working for production, women were forced into brutal labor conditions akin to those of the slaves. They were being compensated, however, at a fourth to a half of what a man would be in the same position.</p>
            <p>In the early to mid 1800s women started to realize the power they held if working in a group. Women were encouraging each other to become educated, which snowballed into intellectual female figures leading the protests. Their protests were about the laws which subjected them to a life of man's choosing. The feminists of this period not only protested for their own rights, but those of the slaves, native americans, and lower class members as well. They understood that a rising tide lifts all boats. Progressive free men also joined the rallies of the feminists, and by 1850 it was clear that change, although there was a long way to go, was on the horizon.</p>
            <p>**It is interesting to note that one of the reasons the women's movement was able to gain traction was through the education of the youth. They had basically the sole responsibility of educating their children, and feminists could use this as an opportunity to raise the next generation in their favor.</p>
            <p class=p-header>Chapter 7: As Long as Grass Grows or Water Runs</p>
            <p>Here, Zinn describes the horrors behind the Native American removal and the United State’s relentless expansion west. If there was ever a story to make white americans feel guilty it is the story of Native Americans being forced out of their native land on which they lived so peacefully. Mostly all that came from the side of the Americans in this expansion were lies, manipulative tactics, and atrocities. The standout culprit representing all these ideologies is 7th president Andrew Jackson.</p>
            <p>I grew up in a period where U.S. history classes began to be somewhat honest about who this guy was, but the depths of his flaws were unbeknownst to me, a 22 year old American, prior to reading this chapter. Whether it was the Creeks, Red Stick, Cherokee, or Chactaw tribes Jackson had plans to push them out of their native land. The go-to strategy consisted of pitting internal and external tribes against each other, separating tribes, and finding any reason for all out war. An example of how the natives americans were pushed out can be seen as the Creek tribe is pushed into and out of georgia. After the battle of horseshoe bend where 800 Creeks were killed, “Jackson and his friends began buying up the seized Creek lands. He got himself appointed treaty commissioner and dictated a treaty which took away half the land of the Creek nation.” Moves like this are seen time and time again, where there is some combination of bloodshed and fraud politics that push the Natives further and further west.</p>
            <p>Chief Black Hawk of Illinois echoes the sentiment of his tribe after being defeated and captured in 1832: “We were becoming like them, hypocrites and liars, adulterous lazy drones, all talkers and no workers… The white men do not scalp the head; but they do worse–they poison the heart…. Farewell, my nation!... Farewell to Black Hawk.” I find this quote another example of the eloquence of Native American culture, as well as damning evidence against the expansionist Americans of the time.</p>
            <p>A Creek man comments on their dealings with the Americans: “Brothers! I have listened to a great many talks from our great father (U.S. Politicians). But they always began and ended in this–”Get a little further; you are too close”. This seems to sum up the era, and can be seen in the Trail of Tears, where 4,000 Cherokees died during a forced march westward.</p>
            <p>Perhaps the most criminal aspect of all is that these removals were celebrated by U.S. elites and some of the populous, as it allowed for more growth and commerce!! These are the roots of western societies ‘disease of more’. </p>
            <p class=p-header>Chapter 8: We Take Nothing by Conquest, Thank God</p>
            <p>The next people to have their freedoms taken in the name of freedom would be the Mexicans. Prior to the 1840’s, Mexico extended through Texas, New Mexico, and all of California.</p>
            <p>My favorite character in this story is Colonel Ethan Allen Hitchcock, who was a soldier first, but completely detested the annexation of Mexico. He wrote about this on the grounds that this violence would only lead to more. The president at the time, James Polk, had a different mindset: expand until the pacific ocean. This of course meant the acquisition of California.</p>
            <p>To start the war Polk needed an excuse, so he sent troops, including Hitchcock, down to the Rio Grande, which was not the agreed upon border at the time. This army would parol around the river until finally, in April 1846, a Colonel was killed and the war was on. As general Taylor wrote to Polk: “Hostilities may now be considered as commenced”.</p>
            <p>I’d like to point out that this is what manifest destiny actually was. Growing up in the U.S. I was told stories of Lewis and Clark discovering America, and trailing a path for those bold enough to move west. The reality is that overspreading through the continent by millions of people would require war and corruption. The government would try to dress the situation up as we see with the needling of Native Americans, and the showing up on Mexico’s doorstep. For the politicians, to be able to blame the enemy for the start of the war was sufficient enough to excuse the decimation to come.</p>
            <p>That’s pretty bleak though, and I did have a more positive note from this chapter. It seems like around this time period, the American people are really starting to protest the government. Of course this has been prevalent since the arrival of the colonists, but here the movements against the elites seem to accelerate. As the war moved into 1847, even the entire Whig party was somewhat anti-war.</p>
            <p>Things became tough for the American army when the conditions of the war were heard by the populous. Less people volunteered as they heard stories of heat, cold, and starvation, and over 9,000 U.S. soldiers deserted. With this the anti-war protests became amplified, and the military had an added pressure to wrap things up. Wrap things up they did, when in February 1848, the Treaty of Guadalupe was signed, and California belonged to the U.S. Mexico did get $15 million dollars for their trouble however, so all's fair the ends fair, right?</p>
            <p>**We take nothing by conquest thank god: refers to both us giving them money and the fact that U.S. elites would declare this war gods will to spread freedom and commerce (sarcasm).</p>
            `,
  },
  post5: {
    id: 5,
    title: "John Maynard Keynes short bio",
    synopsis: "How Keynes bacame a great economist and what he was beyond that",
    author: "Robert Hooker",
    date: "April 16, 2024",
    image: "keynes2.jpg",
    content: `
            <p>Born in Cambridge, England on June 5, 1883, John Maynard Keynes was destined for a life of economics and social theory, as his father Neville was an economist, and his mother Florence was a social reformer. They could not have predicted, however, that their son would earn their surname its own school of thought. From a young age, Keynes showed academic prowess, especially in mathematics, and this combined with a stable upbringing allowed him to become one of the most influential thinkers of the modern world.</p>
    
    <p>A lack of formal education in economics does not hinder a mind like Keynes’, as he is in a class of special individuals whose outlook on the world has clarity unbeknownst to the common man. Fortunately, thoughts like this did not intoxicate his psyche, and he was able to lead a well-intentioned life focused on improving economic outcomes, among other things. His early career saw the same trajectory as his childhood, an acute rise to the top of his discipline. By 1911, Keynes was named editor of <em>The Economic Journal</em>, an accomplishment he would follow up with his first book, <em>Indian Currency and Finance</em>, published in 1913. In retrospect, it is hard to imagine a man with this resume at the age of 30 not becoming a salient pioneer in social thought.</p>
    
    <p>Keynes’ list of contributions to economics is long, but perhaps none more important than his book <em>The General Theory of Employment, Interest and Money</em>. The book argues that employment is dictated by aggregate demand, rather than the price of labor, as was previously thought. It is because of this book that economics students across countless universities are expected to understand that when there is a positive demand shock, the aggregate demand curve shifts right, increasing output and inflation, forcing the aggregate supply curve to shift upward until the economy returns to long-run equilibrium, with inflation permanently higher. Keynes seemed to know this book would have such an enormous impact, so he wrote fearlessly and prophetically. The essence of this is captured well in the first chapter where he states, “the characteristics of the special case assumed by the classical theory happen not to be those of the economic society in which we actually live, with the result that its teaching is misleading and disastrous if we attempt to apply it to the facts of experience.”</p>
    
    <p>As do many visionaries with great intelligence, Keynes comes with a bit of (proper) arrogance. It should not go unsaid that the theories of this book had great influence on struggling economies, and helped policy makers understand that government expenditure has the potential to pull an economy out of recession.</p>
    
    <p>On top of the wide-ranging Keynesian Economics, the economist is also responsible for the multiplier effect, the liquidity preference theory, and of course was a persistent political activist. His work transcends generations, and although highly debated, it has been influential since he introduced it to the world.</p>
        `,
  },
  post6: {
    id: 6,
    title: "AGI Outlook, thoughts",
    synopsis: "Really trying to be bullish on our future prospects here",
    author: "Robert Hooker",
    date: "August 1, 2024",
    image: "agi.jpg",
    content: `<p class="p-header">Preface</p>
<p>I’ve been listening to (Dwarkesh Podcast, Lex Fridman Podcast) and reading (The Alignment Problem, ML papers) a lot about the artificial intelligence conversation over the last ~2 years, and while I don’t believe I can hold a torch to these (yet), I want to layout where I see we stand.</p>

<p class="p-header">Background: Industrial Revolution & The Bomb</p>
<p>What makes AI so enticing to me is the uncertainty of the outcome, both in the long and short run. A large set of people believe it will be a technology that changes the course of humanity, on the order of the industrial revolution or the atomic bomb. These events are interlinked because of their rare, total effect on humanity; however, beyond that, I’d argue their effects were dissimilar.</p>
<p>The industrial revolution introduced, for the first time (to our knowledge), a world where the economic output of humanity would be greater than the sum of humans. This is a technology that in theory and practice would set humanity on a path toward universal prosperity, which seems as good a goal as any. This, of course, is constrained by the intricacies of society, for example, the power-hungry individual, with varying levels of extremity.</p>
<p>The industrial revolution was made possible by collective thinking and idea iteration over time, akin to open-source software engineering. For this reason, among others, it would have a widespread impact on humanity, as numerous fields would adopt new machinery, increasing output exponentially. The bomb, on the other hand, being developed under high security and secrecy (and who could blame the Americans for doing so given the circumstances), would have more of a sudden, psychological impact on our race.</p>
<p>Beyond the immediate horrific impact on the civilians of Nagasaki and Hiroshima, the bomb also created a lasting fear among humanity, that complete annihilation could commence. This fear has fluctuated with global politics since the bomb’s creation, but the threat has remained. At a high level, we have these two events: a singular atrocity that demonstrated our capacity to bring about the end of human times, and a revolution which, while acknowledging its complications, brought prosperity and progress to the human race.</p>
<p>This is all to say that I believe AGI falls somewhere on a spectrum between these two events, or perhaps even beyond them, though exactly where remains unknown. In this essay, I hope to be honest, while providing some hope that this whole deal will end up a net positive.</p>

<p class="p-header">Current Models</p>
<p>Initially, significant gains in model performance were achieved through breakthroughs in training paradigms, such as the introduction of the transformer architecture. However, the focus has now shifted towards a full-fledged competition in terms of compute power and data acquisition. This is not to say that companies are not pouring money into cutting-edge research, but the majority of efforts are towards scaling. Conventionally with new technologies, academic research plays a major role; however, in AI, the costs are so massive that their ability to experiment is greatly hindered. This is akin to the reason OpenAI went from a non-profit to a profit corporation, as it simply takes an incredible amount of capital.</p>
<p>The idea that scaling can lead to AGI cannot yet be proven to be naive; in fact, it could very well be true. Through the evolutions of LLMs thus far, performance has increased at every jump in scale (more data and compute). Given the potential impact of AGI discussed above, it is not surprising that companies are dumping billions of dollars into training their models.</p>
<p>So where do we stand right now? This feels like a good opportunity to acknowledge Mark Zuckerberg. Living a public life since the virality of Facebook, he has seen many praises and criticisms from the public, but now seems to have found a place as some sort of humanitarian/altruist. He seems very sincere in his mission, and I find it admirable that he has open-sourced Meta’s proprietary model. It is because of this that we, the public, get insight into the current progression of what should be a technology that changes our lives. Llama 3.1 was released to the public on July 31st, 2024, and seems to be just as powerful, if not more, than any closed-source model. Thus, Meta says with this model the gap has been closed between open and closed source; however, OpenAI is allegedly in the process of training their new model, so we may see a gap again in the near future.</p>
<p>Llama 3.1 has over 400 billion parameters and is available for the public to train on new datasets and fine-tune. This will hopefully lead to new discoveries that can bring us closer to AGI. With 405B parameters, the model is essentially an incredible personal search assistant. It knows about any topic that has been written about or discussed at length on the internet, and I think this is an incredible technology as is; however, it is not on the order of magnitude of the industrial revolution. The bottleneck to AGI is reasoning, and the Models have shown little to no signs of this, depending on who you ask. In its current state, it will begin to make an impact on everyday life. AIs trained to work, teach, chat, or diagnose will support humans in productivity, learning, existing, and health. This feels like great technology, and, considering the risks, a good place to stop? Nevertheless, that's not how capitalism works, so how can we ensure that future, larger, more capable models are still supporting humanity?</p>

<p class="p-header">Alignment and Interpretability</p>
<p>The high-level goal of alignment is to ensure that whatever AGI is, considering it will be extremely capable, its actions are aligned with human values. There are a large group of people in the AI community whose sole focus is to achieve this alignment, so it would seem we're in good hands. My concern for this topic, however, is that these companies have never demonstrated that they’ll slow down or halt model training in the name of alignment. Since the release of ChatGPT in late 2022, the race has been on. It could be argued that they have been given no reason to stop, since there haven’t been any serious alignment concerns in the models so far. The question is: do we trust these companies, who have massive investment and incentive to deliver, to judge a hazardous alignment situation without bias?</p>
<p>From the above, one thing is clear: we have some interesting years to come in watching what these companies do, but there is one field within alignment that I think deserves praise, and perhaps more funding. Interpretability is the effort to understand how the models are making decisions and making connections. This is simple when analyzing a linear regression model and determining the effect of coefficients on dependent variables, but when a neural network of 405B parameters is introduced, it becomes a scientific wonder. Even still, research teams have come up with discoveries that help us understand the black box that these models are. Namely, <a href="https://www.anthropic.com/research" target="_blank">Anthropic</a> has been dedicated to this type of research and publishes their findings for the public. With this, the same question prevails: can the interpretability researchers keep up with scaling?</p>

<p class="p-header">Economic Impact</p>
<p>Unfortunately, the economic impact of AGI is a highly speculative subject, considering we don’t really know what AGI is yet. There is some world where a superintelligent being renders our entire capitalist system useless, but I prefer to stay optimistic.</p>
<p>The impact of current, or perhaps next-gen models is somewhat tangible and will hopefully be seen further in the coming years. If nothing else, it will increase the output of humanity, as did the industrial revolution. In this aspect, it's simple: more labor potential outputs more labor. This output should lead companies to grow, innovate, and change directions more quickly, which I’d argue will leave us in a better place.</p>
<p>The crux of this growth is whether or not it involves humans, which is clearly essential. There is no doubt that jobs will be replaced by AI in many forms, but it is also true that the technology will create new careers, and perhaps identify those that are intrinsically human. It might seem that we can only hope that the ratio of new jobs to old jobs is greater than one, but I don’t think the hope is related to model performance. Rather, I have hope that humanity, who will ultimately be making the decisions in the foreseeable future, will ensure that fellow humans remain the beneficiaries of new technology, and not the victims.</p>

<p class="p-header">Conclusion</p>
<p>Anyways, I have NASDAQ:META as a BUY</p>
        `,
  },
  post7: {
    id: 7,
    title: "1984 and The Individual",
    synopsis:
      "George Orwell warns of totalitarianism and a loss of indivdualism, is it here?",
    author: "Robert Hooker",
    date: "July 3, 2024",
    image: "1984_landscape.jpg",
    content: `
            	<p>I’ve just finished reading 1984 and have some thoughts on Orwell’s famous warning to humanity on the dangers of government and the potential for totalitarianism, particularly how it relates to the individual in today’s western world. Whatever your stance on such a book it is immediately profound the mental capacity it must have taken to write it. The dystopian society is so well thought out and detailed that it is obvious the man had juggled with these concepts for the greater part of his life.</p> 
	            <p>Part of what prompted me to read this book was the notion that some hold, that our western society is beginning to resemble that of Oceania in 1984 (Aaron Rodgers?). Anyhow, in Oceania, the most valuable asset to The Party is their surveillance infrastructure, which gives them the ability to monitor and control its citizens at all times. Orwell, having died in 1950, could not have seen how our technology would progress, but he understood that a totalitarian government values information above all. To me this is the biggest parallel we have as societies, considering recent issues over data privacy, and the famous global surveillance system leaked by NSA whistleblower Edward Snowden. I can’t help but wonder what Orwell would have thought of the way personal data is conceded, used, and traded in today’s world.</p>  
	            <p>Another aspect of modern society which frightens me is the convergence of thought and the impending departure from individualism. This can be realized in everyday conversation, where people of similar groups are all on the same subjects, and original thoughts are becoming more scarce. I see this mostly as a result of the mass scrolling that my generation has pioneered. The sad bit about this is also the reason why you look around and see so many people locked into their screen, because they think the people around them can’t tell them anything their algorithm hasn’t already. This was a large part of the warning that Orwell gave, that is, Winston is one of the only characters in the novel capable of original thought, due to the mass social and psychological manipulation. This is not to say that control of society is the goal of bytedance, meta, and google, rather I believe these companies and their social media algorithms are simply capitalist ventures that have been optimized to exploit the cognitive weaknesses in the human brain, which is pretty bleak in and of itself. There is hope, however, if you are against these social media algorithms as I am. People across generations are beginning to realize again that face to face human interaction is, in reality, far more fulfilling than these algorithms, opting to leave social media entirely, turning their smart phones dumb, and becoming  mindful of the dopamine exploitation that these apps are.</p>  
	            <p>Beyond that people cite censorship, government war profiteering, and propaganda as other steps we are taking towards Orwell’s dystopian world. I think these are all, obviously, things to remain conscious of, but I remain optimistic, considering I still have a conscience and can write a blog like this without being ‘vaporized’. I feel it is sometimes lost on people that 1984 was an EXTREME warning of how bad total control can be. Writing the book in this manner makes it an incredible read and is what allowed it to be an essential piece of literature. With this, perhaps the sentiment of these societal critics is not that we are literally transcending into this world where we’ll have no right to a conscience and lose any semblance of liberty, but rather that if we are not cautious we could lose our individuality and some of our freedoms, resulting in the halting of humanity’s progression.</p> 
	            <p>So, while clearly 1984 is a denouncement of Stalinism and Totalitarianism as a whole, the warning of a loss of individualism is equally prevalent to the citizens of our society, particularly younger generations, who must continue to combat herd mentality and conformism. In the end, as much of a bummer as this book is, I found it inspiring and invigorating, a stark reminder to act on my own desires and interests, and what a privilege it is to be able to do so!</p>  
        `,
  },
  post8: {
    id: 8,
    title: "Inspiration from Alexander the Great",
    synopsis: "They just don't make them like him anymore!",
    author: "Robert Hooker",
    date: "July 15, 2024",
    image: "alexmap.jpg",
    content: `
            <p class="p-header">Introduction</p>
<p>Much of my fascination with Alexander the Great comes from the fact that he began his Kingship and conquests at the age of 20. Having been 20 years old myself, I can’t imagine any childhood that leads me to think the way Alexander did at this young age, it seems completely unprecedented to me. Furthermore, Alexander, living over 2,000 years ago, had access to a small fraction of the information and resources we do now, so how did he become so impressive? I suppose being prince and future king of Macedonia does have its benefits, including being tutored by Aristotle, but still the stories told of Alex portray that he was born destined to be a hero.</p>
<p>However his education came to be, he left Macedonia with a great understanding of the cultures of the world, and a desire to unify them under his empire. He was smart enough to understand that to win a war you need more military capability, but to win over a people you need to understand their culture and religion.</p>
<p class="p-header">Divine Inspiration</p>
<p>Alexander was inspired by epics like the “Iliad” which helped him create a vision of the future. He was also well versed in the history of war, and knew of sacred landmarks that would be essential in his rise to power. My favorite example of this is Alex’s visit to the Oracle of Siwa, in what is now western Egypt. He famously crossed the brutal desert to receive a reading from the oracle, where his theory was confirmed that he was indeed the son of Zeus-Ammon. This was shortly after he was crowned the Pharaoh of Memphis, and preserver of the god given order. Considering his understanding and belief in religion, his mother's insistence, and his ability to escape death in war, I really don’t blame him, or his followers, at this point for thinking he was a god. In fact, if there was one individual in history that you could convince me was divine, it would be him. With this divine development however some of those close to him became skeptical. Namely, Parmenion essentially thought the power was going to his head, and that the conquest should end in Egypt.</p>
<p class="p-header">Final Days and Legacy</p>
<p>In the end Alexander would die at 32, mysteriously. Leading up to his death he was in Babylon, planning his next conquests. Although he believed there was more work to do, I see his goal as accomplished. He has defeated Persia, liberated Egypt, and unified people across religions and cultures. I think what he understood best was that for Macedonia to succeed, its leaders would need to be diplomatic and genuine. He really seemed to care about his followers, and believed in his cause. Of course, after his death his territories were split up and much of his reform was undone, but I think more importantly, his legacy was set in stone. It's because of his life that people in 2024 have an ancient Greek to admire for his leadership and diplomacy. While I have no plans for conquests, his example of ambitious vision, commitment to cultural understanding, and leadership is something to aspire to.</p>
        `,
  },
};

document.addEventListener("DOMContentLoaded", () => {
  const urlParams = new URLSearchParams(window.location.search);
  const postId = urlParams.get("id");
  const post = posts[postId];

  if (post) {
    document.getElementById("blog-post").innerHTML = `
            <title>${post.title}</title>
            <h1>${post.title}</h1>
            <h3>${post.synopsis}</h3>
            <div class="author">By ${post.author}</div>
            <div class="date">${post.date}</div>
            <img src="assets/${post.image}" alt="${post.title}" class="blog-image">
            <div class="content">${post.content}</div>
        `;
  } else {
    document.getElementById(
      "blog-post"
    ).innerHTML = `<h1 class="notfound">Post not found</h1>`;
  }
});
